package model;
// Generated Nov 11, 2023 12:17:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cartitem generated by hbm2java
 */
@Entity
@Table(name="cartitem"
    ,catalog="j2eeb1"
)
public class Cartitem  implements java.io.Serializable {


     private Integer id;
     private Cart cart;
     private Item item;
     private Integer qty;
     private Double unitprice;
     private Double total;

    public Cartitem() {
    }

	
    public Cartitem(Cart cart, Item item) {
        this.cart = cart;
        this.item = item;
    }
    public Cartitem(Cart cart, Item item, Integer qty, Double unitprice, Double total) {
       this.cart = cart;
       this.item = item;
       this.qty = qty;
       this.unitprice = unitprice;
       this.total = total;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cart", nullable=false)
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item", nullable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    
    @Column(name="unitprice", precision=22, scale=0)
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }

    
    @Column(name="total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


