package model;
// Generated Nov 11, 2023 12:17:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="cart"
    ,catalog="j2eeb1"
)
public class Cart  implements java.io.Serializable {


     private Integer id;
     private Cartstatus cartstatus;
     private Employee employee;
     private Date date;
     private Double total;
     private Boolean isActive;
     private String createduser;
     private Date createdatetime;
     private String lastupdateuser;
     private Date lastupdatedatetime;
     private Set<Cartitem> cartitems = new HashSet<Cartitem>(0);

    public Cart() {
    }

	
    public Cart(Cartstatus cartstatus, Employee employee) {
        this.cartstatus = cartstatus;
        this.employee = employee;
    }
    public Cart(Cartstatus cartstatus, Employee employee, Date date, Double total, Boolean isActive, String createduser, Date createdatetime, String lastupdateuser, Date lastupdatedatetime, Set<Cartitem> cartitems) {
       this.cartstatus = cartstatus;
       this.employee = employee;
       this.date = date;
       this.total = total;
       this.isActive = isActive;
       this.createduser = createduser;
       this.createdatetime = createdatetime;
       this.lastupdateuser = lastupdateuser;
       this.lastupdatedatetime = lastupdatedatetime;
       this.cartitems = cartitems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cartstatus", nullable=false)
    public Cartstatus getCartstatus() {
        return this.cartstatus;
    }
    
    public void setCartstatus(Cartstatus cartstatus) {
        this.cartstatus = cartstatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="createduser", length=100)
    public String getCreateduser() {
        return this.createduser;
    }
    
    public void setCreateduser(String createduser) {
        this.createduser = createduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdatetime", length=19)
    public Date getCreatedatetime() {
        return this.createdatetime;
    }
    
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    
    @Column(name="lastupdateuser", length=100)
    public String getLastupdateuser() {
        return this.lastupdateuser;
    }
    
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastupdatedatetime", length=19)
    public Date getLastupdatedatetime() {
        return this.lastupdatedatetime;
    }
    
    public void setLastupdatedatetime(Date lastupdatedatetime) {
        this.lastupdatedatetime = lastupdatedatetime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cart")
    public Set<Cartitem> getCartitems() {
        return this.cartitems;
    }
    
    public void setCartitems(Set<Cartitem> cartitems) {
        this.cartitems = cartitems;
    }




}


