package model;
// Generated Nov 11, 2023 12:17:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,catalog="j2eeb1"
)
public class Item  implements java.io.Serializable {


     private String id;
     private String name;
     private String imgurl;
     private Boolean isactive;
     private Integer sortkey;
     private Double price;
     private Set<Cartitem> cartitems = new HashSet<Cartitem>(0);

    public Item() {
    }

	
    public Item(String id) {
        this.id = id;
    }
    public Item(String id, String name, String imgurl, Boolean isactive, Integer sortkey, Double price, Set<Cartitem> cartitems) {
       this.id = id;
       this.name = name;
       this.imgurl = imgurl;
       this.isactive = isactive;
       this.sortkey = sortkey;
       this.price = price;
       this.cartitems = cartitems;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=16)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="imgurl")
    public String getImgurl() {
        return this.imgurl;
    }
    
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="sortkey")
    public Integer getSortkey() {
        return this.sortkey;
    }
    
    public void setSortkey(Integer sortkey) {
        this.sortkey = sortkey;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Cartitem> getCartitems() {
        return this.cartitems;
    }
    
    public void setCartitems(Set<Cartitem> cartitems) {
        this.cartitems = cartitems;
    }




}


