package model;
// Generated Nov 11, 2023 12:17:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="status"
    ,catalog="j2eeb1"
)
public class Status  implements java.io.Serializable {


     private String code;
     private String description;

    public Status() {
    }

	
    public Status(String code) {
        this.code = code;
    }
    public Status(String code, String description) {
       this.code = code;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=16)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


